#!/bin/sh
#
#---MKCAUHTML1.   Make the old-style (4.3, webserver login) Caucus start page.
#
#   Input arguments:
#     $1   www hostname
#     $2   Caucus userid
#     $3   sweb alias
#     $4   reg  alias
#     $5   http protocol to use
#
#: CR  4/06/00 12:52 Add sweb and reg aliases
#: CR 03/08/02 11:55 Use 4.4 directory names.
#: CR 06/11/02 add http protcol
#: CR 10/12/05 C5 changes.
#------------------------------------------------------------------------

echo "<HTML>"
echo ""
echo "<HEAD>"
echo "<TITLE>Caucus Start Page</TITLE>"
echo "</HEAD>"
echo ""
echo "<BODY BGCOLOR=\"#FFFFFF\">"
echo ""
echo "<TABLE WIDTH=100% CELLSPACING=0 CELLPADDING=0 BGCOLOR=\"#FFFFFF\">"
echo "<TR>"
echo "<TD VALIGN=bottom>"
echo "   <H1>Start Page</H1>"
echo "</TD>"
echo "<TD VALIGN=bottom ALIGN=right>"
echo "   <A HREF=\"$5://caucuscare.com\"><IMG"
echo "       SRC=\"$5://$1/~$2/GIF50/lcaucus0.gif\" WIDTH=144 HEIGHT=47"
echo "       ALT=\"Caucus\" BORDER=0></A>"
echo "</TD>"
echo "</TABLE>"
echo ""
echo "<P>"
echo "&nbsp;Start here to use the Caucus conferencing system."
echo ""
echo "<P>"
echo "<UL>"
echo "<TABLE>"
echo "<TR>"
echo "<TD><B>First time at this page?</B></TD>"
echo "<TD>&nbsp;&nbsp;&nbsp;</TD>"
echo ""
echo "<TD>You may "
echo " <A HREF=\"$5://$1/$4/swebsock/0/0/CC51/reg/register.cml\">"
echo "    self-register</A> a userid and password.</TD>"
echo ""

echo "<TR><TD>&nbsp;</TD>"
echo "<TR>"
echo "<TD><B>Forgot your password?</B></TD>"
echo "<TD>&nbsp;&nbsp;&nbsp;</TD>"
echo "<TD>You may "
echo " <A HREF=\"$5://$1/$4/swebsock/0/0/CC51/reg/reset.cml\">"
echo "    reset</A> your password and have it e-mailed to you.</TD>"
echo ""

echo "<TR><TD>&nbsp;</TD>"
echo "<TR>"
echo "<TD><B>Already have a userid?</B></TD>"
echo "<TD></TD>"
echo "<TD>Go on to the"
echo " <A"
echo " HREF=\"$5://$1/$3/swebsock/0/0/CC51/main/center.cml?0+0+x+x+x+x+x+x\">"
echo "     Caucus Center</A>.</TD>"
echo "</TABLE>"
echo "</UL>"
echo ""
echo "<P>"
echo "<HR>"
echo "</BODY>"
echo "</HTML>"

#------------------------------------------------------------------------
